add docker-2
Otus-DevOps-2023-07/dmitriy-kutepow_microservices pull request #1
Opened 2023-10-18 15:40 UTC by dmitriy-kutepow

# Выполнено ДЗ №13

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
1.Установил Docker, Docker-compose, Docker-machine.
2.Успешно проверил работу докер с помошью docker run hello-world
3.Инициализировал консоль яндекс клауд yc init
4.Создал докер-хост
5.Инициализировал окружение докер на докер-хост
6.Написал Докерфайл и конфиги
7.Собрал образ
8.Запустил контейнер
9.Зарегистрировался в докер-хаб
10.Запушил получившийся образ в докер-хаб
11.Проверил работоспособность на локальной машине.

## Как запустить проект:
 - Перейти в дирикторию docker-monolith и собрать образ с помошью команд из ридми.
 - Запустить контейнер локально или на удалённом докер хосте с помошью команд из ридми.

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2023-10-18 19:39 UTC, mrgreyves requested changes
Здравствуйте!)
Вам нужно добавить тесты
Просто перенесите их из старого репозитория =)
Приключение на 5 минуток =)

2023-10-22 08:30 UTC, dmitriy-kutepow commented
Хмм, подгрузил, но почему-то не появляется.

2023-10-28 12:45 UTC, mrgreyves approved these changes
Здравствуйте!)
Надеюсь что в следующий раз заработает =)

2023-10-28 12:45 UTC, mrgreyves commented on .github/ PULL_REQUEST_TEMPLATE.md
> +# Выполнено ДЗ №
Имя файла вначале с пробелом =)

2023-11-04 09:46 UTC, merged